import { ControlType } from '@joka00.dev/libs/data-access';
import { IsLabelVisible } from './components/config-group/config-group.component';

export const timezones = [
  'Europe/Andorra',
  'Asia/Dubai',
  'Asia/Kabul',
  'Europe/Tirane',
  'Asia/Yerevan',
  'Antarctica/Casey',
  'Antarctica/Davis',
  'Antarctica/DumontDUrville',
  'Antarctica/Mawson',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Antarctica/Syowa',
  'Antarctica/Troll',
  'Antarctica/Vostok',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Cordoba',
  'America/Argentina/Salta',
  'America/Argentina/Jujuy',
  'America/Argentina/Tucuman',
  'America/Argentina/Catamarca',
  'America/Argentina/La_Rioja',
  'America/Argentina/San_Juan',
  'America/Argentina/Mendoza',
  'America/Argentina/San_Luis',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Ushuaia',
  'Pacific/Pago_Pago',
  'Europe/Vienna',
  'Australia/Lord_Howe',
  'Antarctica/Macquarie',
  'Australia/Hobart',
  'Australia/Currie',
  'Australia/Melbourne',
  'Australia/Sydney',
  'Australia/Broken_Hill',
  'Australia/Brisbane',
  'Australia/Lindeman',
  'Australia/Adelaide',
  'Australia/Darwin',
  'Australia/Perth',
  'Australia/Eucla',
  'Asia/Baku',
  'America/Barbados',
  'Asia/Dhaka',
  'Europe/Brussels',
  'Europe/Sofia',
  'Atlantic/Bermuda',
  'Asia/Brunei',
  'America/La_Paz',
  'America/Noronha',
  'America/Belem',
  'America/Fortaleza',
  'America/Recife',
  'America/Araguaina',
  'America/Maceio',
  'America/Bahia',
  'America/Sao_Paulo',
  'America/Campo_Grande',
  'America/Cuiaba',
  'America/Santarem',
  'America/Porto_Velho',
  'America/Boa_Vista',
  'America/Manaus',
  'America/Eirunepe',
  'America/Rio_Branco',
  'America/Nassau',
  'Asia/Thimphu',
  'Europe/Minsk',
  'America/Belize',
  'America/St_Johns',
  'America/Halifax',
  'America/Glace_Bay',
  'America/Moncton',
  'America/Goose_Bay',
  'America/Blanc-Sablon',
  'America/Toronto',
  'America/Nipigon',
  'America/Thunder_Bay',
  'America/Iqaluit',
  'America/Pangnirtung',
  'America/Atikokan',
  'America/Winnipeg',
  'America/Rainy_River',
  'America/Resolute',
  'America/Rankin_Inlet',
  'America/Regina',
  'America/Swift_Current',
  'America/Edmonton',
  'America/Cambridge_Bay',
  'America/Yellowknife',
  'America/Inuvik',
  'America/Creston',
  'America/Dawson_Creek',
  'America/Fort_Nelson',
  'America/Vancouver',
  'America/Whitehorse',
  'America/Dawson',
  'Indian/Cocos',
  'Europe/Zurich',
  'Africa/Abidjan',
  'Pacific/Rarotonga',
  'America/Santiago',
  'America/Punta_Arenas',
  'Pacific/Easter',
  'Asia/Shanghai',
  'Asia/Urumqi',
  'America/Bogota',
  'America/Costa_Rica',
  'America/Havana',
  'Atlantic/Cape_Verde',
  'America/Curacao',
  'Indian/Christmas',
  'Asia/Nicosia',
  'Asia/Famagusta',
  'Europe/Prague',
  'Europe/Berlin',
  'Europe/Copenhagen',
  'America/Santo_Domingo',
  'Africa/Algiers',
  'America/Guayaquil',
  'Pacific/Galapagos',
  'Europe/Tallinn',
  'Africa/Cairo',
  'Africa/El_Aaiun',
  'Europe/Madrid',
  'Africa/Ceuta',
  'Atlantic/Canary',
  'Europe/Helsinki',
  'Pacific/Fiji',
  'Atlantic/Stanley',
  'Pacific/Chuuk',
  'Pacific/Pohnpei',
  'Pacific/Kosrae',
  'Atlantic/Faroe',
  'Europe/Paris',
  'Europe/London',
  'Asia/Tbilisi',
  'America/Cayenne',
  'Africa/Accra',
  'Europe/Gibraltar',
  'America/Godthab',
  'America/Danmarkshavn',
  'America/Scoresbysund',
  'America/Thule',
  'Europe/Athens',
  'Atlantic/South_Georgia',
  'America/Guatemala',
  'Pacific/Guam',
  'Africa/Bissau',
  'America/Guyana',
  'Asia/Hong_Kong',
  'America/Tegucigalpa',
  'America/Port-au-Prince',
  'Europe/Budapest',
  'Asia/Jakarta',
  'Asia/Pontianak',
  'Asia/Makassar',
  'Asia/Jayapura',
  'Europe/Dublin',
  'Asia/Jerusalem',
  'Asia/Kolkata',
  'Indian/Chagos',
  'Asia/Baghdad',
  'Asia/Tehran',
  'Atlantic/Reykjavik',
  'Europe/Rome',
  'America/Jamaica',
  'Asia/Amman',
  'Asia/Tokyo',
  'Africa/Nairobi',
  'Asia/Bishkek',
  'Pacific/Tarawa',
  'Pacific/Enderbury',
  'Pacific/Kiritimati',
  'Asia/Pyongyang',
  'Asia/Seoul',
  'Asia/Almaty',
  'Asia/Qyzylorda',
  'Asia/Qostanay', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
  'Asia/Aqtobe',
  'Asia/Aqtau',
  'Asia/Atyrau',
  'Asia/Oral',
  'Asia/Beirut',
  'Asia/Colombo',
  'Africa/Monrovia',
  'Europe/Vilnius',
  'Europe/Luxembourg',
  'Europe/Riga',
  'Africa/Tripoli',
  'Africa/Casablanca',
  'Europe/Monaco',
  'Europe/Chisinau',
  'Pacific/Majuro',
  'Pacific/Kwajalein',
  'Asia/Yangon',
  'Asia/Ulaanbaatar',
  'Asia/Hovd',
  'Asia/Choibalsan',
  'Asia/Macau',
  'America/Martinique',
  'Europe/Malta',
  'Indian/Mauritius',
  'Indian/Maldives',
  'America/Mexico_City',
  'America/Cancun',
  'America/Merida',
  'America/Monterrey',
  'America/Matamoros',
  'America/Mazatlan',
  'America/Chihuahua',
  'America/Ojinaga',
  'America/Hermosillo',
  'America/Tijuana',
  'America/Bahia_Banderas',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Africa/Maputo',
  'Africa/Windhoek',
  'Pacific/Noumea',
  'Pacific/Norfolk',
  'Africa/Lagos',
  'America/Managua',
  'Europe/Amsterdam',
  'Europe/Oslo',
  'Asia/Kathmandu',
  'Pacific/Nauru',
  'Pacific/Niue',
  'Pacific/Auckland',
  'Pacific/Chatham',
  'America/Panama',
  'America/Lima',
  'Pacific/Tahiti',
  'Pacific/Marquesas',
  'Pacific/Gambier',
  'Pacific/Port_Moresby',
  'Pacific/Bougainville',
  'Asia/Manila',
  'Asia/Karachi',
  'Europe/Warsaw',
  'America/Miquelon',
  'Pacific/Pitcairn',
  'America/Puerto_Rico',
  'Asia/Gaza',
  'Asia/Hebron',
  'Europe/Lisbon',
  'Atlantic/Madeira',
  'Atlantic/Azores',
  'Pacific/Palau',
  'America/Asuncion',
  'Asia/Qatar',
  'Indian/Reunion',
  'Europe/Bucharest',
  'Europe/Belgrade',
  'Europe/Kaliningrad',
  'Europe/Moscow',
  'Europe/Simferopol',
  'Europe/Kirov',
  'Europe/Astrakhan',
  'Europe/Volgograd',
  'Europe/Saratov',
  'Europe/Ulyanovsk',
  'Europe/Samara',
  'Asia/Yekaterinburg',
  'Asia/Omsk',
  'Asia/Novosibirsk',
  'Asia/Barnaul',
  'Asia/Tomsk',
  'Asia/Novokuznetsk',
  'Asia/Krasnoyarsk',
  'Asia/Irkutsk',
  'Asia/Chita',
  'Asia/Yakutsk',
  'Asia/Khandyga',
  'Asia/Vladivostok',
  'Asia/Ust-Nera',
  'Asia/Magadan',
  'Asia/Sakhalin',
  'Asia/Srednekolymsk',
  'Asia/Kamchatka',
  'Asia/Anadyr',
  'Asia/Riyadh',
  'Pacific/Guadalcanal',
  'Indian/Mahe',
  'Africa/Khartoum',
  'Europe/Stockholm',
  'Asia/Singapore',
  'America/Paramaribo',
  'Africa/Juba',
  'Africa/Sao_Tome',
  'America/El_Salvador',
  'Asia/Damascus',
  'America/Grand_Turk',
  'Africa/Ndjamena',
  'Indian/Kerguelen',
  'Asia/Bangkok',
  'Asia/Dushanbe',
  'Pacific/Fakaofo',
  'Asia/Dili',
  'Asia/Ashgabat',
  'Africa/Tunis',
  'Pacific/Tongatapu',
  'Europe/Istanbul',
  'America/Port_of_Spain',
  'Pacific/Funafuti',
  'Asia/Taipei',
  'Europe/Kiev',
  'Europe/Uzhgorod',
  'Europe/Zaporozhye',
  'Pacific/Wake',
  'America/New_York',
  'America/Detroit',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/Indiana/Indianapolis',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Vevay',
  'America/Chicago',
  'America/Indiana/Tell_City',
  'America/Indiana/Knox',
  'America/Menominee',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'America/North_Dakota/Beulah',
  'America/Denver',
  'America/Boise',
  'America/Phoenix',
  'America/Los_Angeles',
  'America/Anchorage',
  'America/Juneau',
  'America/Sitka',
  'America/Metlakatla',
  'America/Yakutat',
  'America/Nome',
  'America/Adak',
  'Pacific/Honolulu',
  'America/Montevideo',
  'Asia/Samarkand',
  'Asia/Tashkent',
  'America/Caracas',
  'Asia/Ho_Chi_Minh',
  'Pacific/Efate',
  'Pacific/Wallis',
  'Pacific/Apia',
  'Africa/Johannesburg',
].sort();

export const supportedLocales = [
  'af_ZA.UTF-8',
  'sq_AL.UTF-8',
  'ar_SA.UTF-8',
  'eu_ES.UTF-8',
  'be_BY.UTF-8',
  'bs_BA.UTF-8',
  'bg_BG.UTF-8',
  'ca_ES.UTF-8',
  'hr_HR.UTF-8',
  'zh_CN.UTF-8',
  'zh_TW.UTF-8',
  'cs_CZ.UTF-8',
  'da_DK.UTF-8',
  'nl_NL.UTF-8',
  'en.UTF-8',
  'en_US.UTF-8',
  'et_EE.UTF-8',
  'fa_IR.UTF-8',
  'fil_PH.UTF-8',
  'fi_FI.UTF-8',
  'fr_FR.UTF-8',
  'fr_CH.UTF-8',
  'fr_BE.UTF-8',
  'ga.UTF-8',
  'gl_ES.UTF-8',
  'ka_GE.UTF-8',
  'de_DE.UTF-8',
  'el_GR.UTF-8',
  'gu.UTF-8',
  'he_IL.utf8',
  'hi_IN.UTF-8',
  'hu.UTF-8',
  'is_IS.UTF-8',
  'id_ID.UTF-8',
  'it_IT.UTF-8',
  'ja_JP.UTF-8',
  'kn_IN.UTF-8',
  'km_KH.UTF-8',
  'ko_KR.UTF-8',
  'lo_LA.UTF-8',
  'lt_LT.UTF-8',
  'lat.UTF-8',
  'ml_IN.UTF-8',
  'ms_MY.UTF-8',
  'mi_NZ.UTF-8',
  'mi_NZ.UTF-8',
  'mn.UTF-8	',
  'no_NO.UTF-8',
  'nn_NO.UTF-8',
  'pl.UTF-8',
  'pt_PT.UTF-8',
  'pt_BR.UTF-8',
  'ro_RO.UTF-8',
  'ru_RU.UTF-8',
  'mi_NZ.UTF-8',
  'sr_CS.UTF-8',
  'sk_SK.UTF-8',
  'sl_SI.UTF-8',
  'so_SO.UTF-8',
  'es_ES.UTF-8',
  'sv_SE.UTF-8',
  'tl.UTF-8',
  'ta_IN.UTF-8',
  'th_TH.UTF-8',
  'mi_NZ.UTF-8',
  'tr_TR.UTF-8',
  'uk_UA.UTF-8',
  'vi_VN.UTF-8',
].sort();

export const supportedLocalesWithSuffix = supportedLocales.map(
  (locale) => `${locale}/UTF-8`,
);

export const DESCRIPTIONS = [
  // {
  //   key: 'boot',
  //   label: 'Boot',
  //   children: [
  //     {
  //       key: 'quietboot',
  //       label: 'Quiet boot',
  //       children: [
  //         {
  //           key: 'enable',
  //           label: 'Enables or disables quiet boot mode (enables plymouth)',
  //           controlType: ControlType.checkbox,
  //         },
  //       ],
  //     },
  //     {
  //       key: 'uefi',
  //       label: 'UEFI',
  //       children: [
  //         {
  //           key: 'enable',
  //           label: 'Enables or disables UEFI boot mode',
  //           controlType: ControlType.checkbox,
  //         },
  //         {
  //           key: 'secureboot',
  //           label: 'Enables or disables secure boot in UEFI mode',
  //           controlType: ControlType.checkbox,
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   key: 'home',
  //   label: 'Home',
  //   children: [
  //     {
  //       key: 'users',
  //       label: 'List of managed users',
  //       controlType: ControlType['multi-select'],
  //     },
  //   ],
  // },
  {
    key: 'core',
    label: 'Core',
    children: [
      {
        key: 'disableDefaults',
        label: 'Disables default settings if set to true',
        controlType: ControlType.checkbox,
      },
      {
        key: 'locale',
        label: 'Locale',
        children: [
          {
            key: 'defaultLocale',
            label: 'Sets the default locale for the system',
            controlType: ControlType.select,
            options: supportedLocales,
          },
          {
            key: 'supportedLocales',
            label: 'List of supported locales',
            controlType: ControlType['multi-select'],
            options: supportedLocalesWithSuffix,
          },
          {
            key: 'timeZone',
            label: "Sets the system's time zone",
            controlType: ControlType.select,
            options: timezones,
          },
        ],
      },
      {
        key: 'network',
        label: 'Network',
        children: [
          {
            key: 'domain',
            label: 'Sets the network domain',
            controlType: ControlType.text,
          },
          {
            key: 'services',
            label: 'Services',
            children: [
              {
                key: 'enableAvahi',
                label: 'Enables or disables the Avahi service',
                controlType: ControlType.checkbox,
              },
              {
                key: 'enableNetworkManager',
                label: 'Enables or disables the NetworkManager service',
                controlType: ControlType.checkbox,
              },
              {
                key: 'enableResolved',
                label: 'Enables or disables the systemd-resolved service',
                controlType: ControlType.checkbox,
              },
            ],
          },
        ],
      },
      {
        key: 'securityRules',
        label: 'Security rules',
        children: [
          {
            key: 'enable',
            label: 'Enable or disable hardened security rules',
            typeControl: ControlType.checkbox,
          },
        ],
      },
      {
        key: 'shells',
        label: 'Shells',
        children: [
          {
            key: 'fish',
            label: 'Fish',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Fish shell',
                controlType: ControlType.checkbox,
              },
            ],
          },
          {
            key: 'zsh',
            label: 'Zsh',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Zsh shell',
                controlType: ControlType.checkbox,
              },
            ],
          },
        ],
      },
      {
        key: 'storage',
        label: 'Storage',
        children: [
          {
            key: 'enablePersistence',
            label: 'Enables or disables persistence',
            controlType: ControlType.checkbox,
          },
          {
            key: 'swapFile',
            label: 'Swap file',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the swap file',
                controlType: ControlType.checkbox,
              },
              {
                key: 'path',
                label: 'Path to the swap file',
                controlType: ControlType.text,
              },
              {
                key: 'size',
                label: 'Size of the swap file',
                controlType: 'number',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'desktop',
    label: 'Desktop',
    children: [
      {
        key: 'gamemode',
        label: 'Gamemode',
        children: [
          {
            key: 'enable',
            label: 'Enables or disables the Gamemode',
            controlType: ControlType.checkbox,
          },
        ],
      },
      {
        key: 'wayland',
        label: 'Wayland',
        children: [
          {
            key: 'desktopManager',
            label: 'Desktop managers',
            children: [
              {
                key: 'gnome',
                label: 'Gnome',
                children: [
                  {
                    key: 'enable',
                    label: 'Enables or disables the Gnome desktop environment',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
              {
                key: 'plasma6',
                label: 'Plasma/KDE',
                children: [
                  {
                    key: 'enable',
                    label:
                      'Enables or disables the Plasma 6 desktop environment',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
            ],
          },
          {
            key: 'displayManager',
            label: 'Display managers',
            children: [
              {
                key: 'gdm',
                label: 'GDM',
                children: [
                  {
                    key: 'enable',
                    label: 'Enables or disables the GDM display manager',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
            ],
          },
          {
            key: 'windowManager',
            label: 'Window managers',
            children: [
              {
                key: 'hyprland',
                label: 'Hyprland',
                children: [
                  {
                    key: 'enable',
                    label: 'Enables or disables the Hyprland window manager',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
              {
                key: 'sway',
                label: 'Sway',
                children: [
                  {
                    key: 'enable',
                    label: 'Enables or disables the Sway window manager',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  // {
  //   key: 'hardware',
  //   label: 'Hardware',
  //   children: [
  //     {
  //       key: 'cpu',
  //       label: 'CPU',
  //       children: [
  //         {
  //           key: 'intel',
  //           label: 'Intel',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables Intel CPU support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //         {
  //           key: 'amd',
  //           label: 'AMD',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables AMD CPU support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       key: 'gpu',
  //       label: 'GPU',
  //       children: [
  //         {
  //           key: 'intel',
  //           label: 'Intel',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables Intel GPU support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //         {
  //           key: 'amd',
  //           label: 'AMD',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables AMD GPU support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //         {
  //           key: 'nvidia',
  //           label: 'Nvidia',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables Nvidia GPU support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       key: 'misc',
  //       label: 'Miscellaneous',
  //       children: [
  //         {
  //           key: 'trezor',
  //           label: 'Trezor bridge',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables the Trezor bridge',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //         {
  //           key: 'xbox',
  //           label: 'Xbox',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables Xbox controller support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //         {
  //           key: 'yubikey',
  //           label: 'Yubikey',
  //           children: [
  //             {
  //               key: 'enable',
  //               label: 'Enables or disables Yubikey support',
  //               controlType: ControlType.checkbox,
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },
  {
    key: 'server',
    label: 'Server',
    children: [
      {
        key: 'auth',
        label: 'Authentication services',
        children: [
          {
            key: 'freeipa',
            label: 'FreeIPA',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the FreeIPA server',
                controlType: ControlType.checkbox,
              },
            ],
          },
          {
            key: 'keycloak',
            label: 'Keycloak',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Keycloak service',
                controlType: ControlType.checkbox,
              },
            ],
          },
        ],
      },
      {
        key: 'cache',
        label: 'Cache server',
        children: [
          {
            key: 'enable',
            label: 'Enables or disables the cache server',
            controlType: ControlType.checkbox,
          },
        ],
      },
      {
        key: 'hydra',
        label: 'Hydra',
        children: [
          {
            key: 'enable',
            label: 'Enables or disables the Hydra server',
            controlType: ControlType.checkbox,
          },
        ],
      },
      {
        key: 'minecraft',
        label: 'Minecraft server',
        children: [
          {
            key: 'enable',
            label: 'Enables or disables the Minecraft server',
            controlType: ControlType.checkbox,
          },
        ],
      },
      {
        key: 'databases',
        label: 'Databases',
        children: [
          {
            key: 'mysql',
            label: 'MySQL',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the MySQL database',
                controlType: ControlType.checkbox,
              },
            ],
          },
          {
            key: 'postgresql',
            label: 'PostgreSQL',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the PostgreSQL database',
                controlType: ControlType.checkbox,
              },
            ],
          },
        ],
      },
      {
        key: 'services',
        label: 'Server services',
        children: [
          {
            key: 'web',
            label: 'Web',
            children: [
              {
                key: 'acme',
                label: 'ACME',
                children: [
                  {
                    key: 'enable',
                    label: 'Enables or disables the ACME service',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
              {
                key: 'nginx',
                label: 'Nginx',
                children: [
                  {
                    key: 'enable',
                    label: 'Enables or disables the Nginx service',
                    controlType: ControlType.checkbox,
                  },
                ],
              },
            ],
          },
          {
            key: 'fail2ban',
            label: 'Fail2Ban',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Fail2ban service',
                typeControl: ControlType.checkbox,
              },
            ],
          },
          {
            key: 'headscale',
            label: 'Headscale',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Headscale service',
                controlType: ControlType.checkbox,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'utils',
    label: 'Utilities',
    children: [
      {
        key: 'kdeconnect',
        label: 'KDE Connect',
        children: [
          {
            key: 'enable',
            label: 'Enables or disables the KDE Connect',
            controlType: ControlType.checkbox,
          },
        ],
      },
      {
        key: 'virtualisation',
        label: 'Virtualisation',
        children: [
          {
            key: 'docker',
            label: 'Docker',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Docker',
                controlType: ControlType.checkbox,
              },
            ],
          },
          {
            key: 'podman',
            label: 'Podman',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the Podman',
                controlType: ControlType.checkbox,
              },
            ],
          },
          {
            key: 'libvirtd',
            label: 'Libvirtd',
            children: [
              {
                key: 'enable',
                label: 'Enables or disables the libvirtd',
                controlType: ControlType.checkbox,
              },
            ],
          },
        ],
      },
    ],
  },
];
